import { ApiProperty } from '@nestjs/swagger';
import { User } from 'src/user/entities/user.entity'; // Assuming a User entity exists

export class Organization {

  @ApiProperty({
    description: 'User Id, generated by uuid',
    nullable: false,
    required: true,
    type: 'string',
    example: '97e05e9c-7491-4098-ab4d-ef66c68eb02d',
  })
  id: number;

  @ApiProperty({
    description: 'Organization Name',
    nullable: false,
    required: true,
    type: 'string',
    example: 'Acme Corporation',
  })
  name: string;

  @ApiProperty({
    description: 'Organization Address',
    nullable: true,
    required: false,
    type: 'string',
    example: '123 Business St, New York, NY',
  })
  address?: string;

  @ApiProperty({
    description: 'User Id (Foreign key to User)',
    nullable: false,
    required: true,
    type: 'number',
    example: 1,
  })
  userId: number;

  @ApiProperty({
    description: 'User associated with the organization',
    nullable: false,
    required: true,
    type: () => User, // Assuming you want to show the User details along with the Organization
  })
  user: User;

  @ApiProperty({
    description: 'Date when the organization was created',
    nullable: false,
    required: true,
    type: 'string',
    example: '2024-09-29T00:00:00.000Z',
  })
  createdAt: Date;

  @ApiProperty({
    description: 'Date when the organization was last updated',
    nullable: false,
    required: true,
    type: 'string',
    example: '2024-09-29T00:00:00.000Z',
  })
  updatedAt: Date;
}
